--With oracle, you must manually create your changelog table.  Sorry. :(
--If you know of a good way to replicate something similar to what's in the EnsureChangeLogExists
--script in the mssql directory, please let me know.